version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '.'
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'Europe/Rome'
    groups:
      node-deps:
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
    target-branch: 'main'
    commit-message:
      prefix: 'Update NPM deps'
    labels:
      - 'npm'
      - 'dependencies'
    assignees:
      - 'cowuake'
